### ISSUE TITLE
error in starting the pods

### ISSUE THREAD

**Issue by kishorerv93** [carlosedp/prometheus-operator-ARM#4]
Failed to pull image "carlosedp/node_exporter:v0.15.2": rpc error: code = Unknown desc = no supported platform found in manifest list
<img width="1390" alt="screen shot 2018-07-18 at 1 57 58 pm" src="https://user-images.githubusercontent.com/22155528/42898984-b1c5f2de-8a92-11e8-99c8-3cfc9245394d.png">

**Comment by carlosedp** [comment]
You might be using these images on amd64 platform. I currently only build for ARM and ARM64:

Image: carlosedp/node_exporter:v0.15.2
 * Manifest List: Yes
 * Supported platforms:
   - linux/arm/undefined
   - linux/arm64/undefined

I will try to add AMD64 to it soon.
