### ISSUE TITLE
how does rpi_up work?

### ISSUE THREAD

**Issue by maxpshaw** [carlosedp/prometheus-operator-ARM#5]
Hello @carlosedp ,

Can you shed some light on rpi_up? is it a metric? how does it work?

https://github.com/carlosedp/prometheus-operator-ARM/blob/26fe27848558acbbb2e31983be7411028892612d/grafana-dashboards/Kubernetes%20cluster%20monitoring.json#L216

**Comment by carlosedp** [comment]
Actually the older metric from rpi_exporter was called rpi_up. It doesn't exist anymore. I replaced with the "up" function. Already commited the new versions into the repo. take a look.
