### ISSUE TITLE
Error on "make"

### ISSUE THREAD

**Issue by gamename** [carlosedp/prometheus-operator-ARM#9]
Hi,

I followed the installation process an the "make vendor" steps. Everything worked. 

Then I started to run plain "make" and got the following error:
```
$ make
rm -rf manifests
./scripts/build.sh main.jsonnet
+ set -o pipefail
+ rm -rf manifests
+ mkdir manifests
+ jsonnet -J vendor -m manifests main.jsonnet
+ xargs '-I{}' sh -c 'cat {} | gojsontoyaml > {}.yaml; rm -f {}' -- '{}'
./scripts/build.sh: line 15: jsonnet: command not found
Makefile:12: recipe for target 'manifests' failed
make: *** [manifests] Error 127
```

Here is my OS info:
```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
HYPRIOT_OS="HypriotOS/armhf"
HYPRIOT_OS_VERSION="v2.0.1"
HYPRIOT_DEVICE="Raspberry Pi"
HYPRIOT_IMAGE_VERSION="v1.9.0"
```

Here is my k8s info:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/arm"}
```

What am I doing wrong?

**Comment by carlosedp** [comment]
Fixed in https://github.com/carlosedp/prometheus-operator-ARM/commit/2d042dcd501e750a0fdf16b0c3e340b5d0e17703.

Now the Makefile installs the required utilities (jsonnet, jsonner-bundler, gojsontoyaml) if not present.

You need Go installed.

**Comment by DrumSergio** [comment]
Same error, latest commit pulled, Go installed too.
Tested on a Raspbian 10 Lite.

**Comment by fufiderheld** [comment]
I am having a problem with the `make vendor` command. I am getting the message
`root@k3sserverpi:/home/pi/cluster-monitoring# make vendor`
`Installing jsonnet-bundler`
`package github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest: can only use path@version syntax with 'go get'
make: *** [Makefile:52: /bin/go/bin/jb] Error 1`
I installed go and try to install it on PI 4 bullseye
I have K3S installed and in the vars.jsonnet k3s is enabled, also maste rIP and SuffixDomain is entered. 
What am I missing?
With the command `go env` the GOPATH is set correctly i guess
Here is the output:
`root@k3sserverpi:/# go env`
`GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/bin/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/bin/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.15"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.15/pkg/tool/linux_arm64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build434279315=/tmp/go-build -gno-record-gcc-switches"`

Any help apreciated.
